# -*- coding: utf-8 -*-
"""tds-w8-ga.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/sampriti-sr/1fd06d099befc03f71cfed98ea4150f3/tds-w8-ga.ipynb

Install Streamlit Library
"""

!pip install streamlit

"""Largest among three numbers"""

import streamlit as st

"""Code for the above"""

@st.cache
def largest_among_three(a, b, c):
    if a > b and a > c:
        return a
    elif b > a and b > c:
        return b
    else:
        return c

def app():
    st.title('Largest Among Three')
    st.write('Enter three numbers to find the largest among them:')
    a = st.number_input('Enter the first number')
    b = st.number_input('Enter the second number')
    c = st.number_input('Enter the third number')
    if st.button('Find Largest'):
        largest = largest_among_three(a, b, c)
        st.success(f'The largest among {a}, {b}, and {c} is {largest}')

"""Run StreamLit"""

if __name__ == '__main__':
    app()